// demos/ng-wc/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  data = {
    label: 'Show me',
    action: () => alert('Hello from Angular')
  };

  title: string;

  handleInput({ target: { value } }) {
    this.title = value;
  }
}

<img
  width="200"
  alt="Angular Logo"
  src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
/>

<div class="wcs">
  <h3>{{ title || 'Will show when you type' }}</h3>
  <app-textfield (change)="handleInput($event)" placeholder="Type something"></app-textfield>
  <app-button [data]="data"></app-button>
</div>

// demos/react-wc/src/App.js
import React, { useState } from 'react';
import logo from './logo.svg';
import './App.css';
import reactifyWc from 'reactify-wc';

const Textfield = reactifyWc('app-textfield');
const Button = reactifyWc('app-button');

function App() {
    const [title, setTitle] = useState();

    return (
        <div className="App">
            <header className="App-header">
                <img src={logo} className="App-logo" alt="logo" />
                <div className="App-wcs">
                    <h3>{title || 'Will show when you type'}</h3>
                    <Textfield
                        placeholder="Type something"
                        onChange={({ target }) => {
                            setTitle(target.value);
                        }}
                    />
                    <Button
                        data={{
                            label: 'Show me',
                            action: () => alert('Hello from React')
                        }}
                    />
                </div>
            </header>
        </div>
    );
}

export default App;
